/* Icons used across the site (from the lucide icon set).
   Content files refer to icons by the names listed below, e.g. icon: "shield". */

import {
  BadgeCheck,
  BookOpen,
  Briefcase,
  Building2,
  CircleCheck,
  ClipboardCheck,
  Clock,
  Database,
  Download,
  EyeOff,
  FileLock2,
  FilePen,
  FileSearch,
  FileText,
  Fingerprint,
  GitCompareArrows,
  Globe,
  History,
  KeyRound,
  Landmark,
  Layers,
  Library,
  ListChecks,
  Lock,
  MessageSquare,
  PenLine,
  Radar,
  Scale,
  ScanSearch,
  Server,
  ShieldCheck,
  Target,
  Upload,
  UserCheck,
  Users,
  type LucideProps,
} from "lucide-react";

const icons = {
  badge: BadgeCheck,
  book: BookOpen,
  briefcase: Briefcase,
  building: Building2,
  check: CircleCheck,
  clipboard: ClipboardCheck,
  clock: Clock,
  compare: GitCompareArrows,
  database: Database,
  download: Download,
  eyeOff: EyeOff,
  fileLock: FileLock2,
  filePen: FilePen,
  fileSearch: FileSearch,
  fileText: FileText,
  fingerprint: Fingerprint,
  globe: Globe,
  history: History,
  key: KeyRound,
  landmark: Landmark,
  layers: Layers,
  library: Library,
  list: ListChecks,
  lock: Lock,
  message: MessageSquare,
  pen: PenLine,
  radar: Radar,
  scale: Scale,
  scan: ScanSearch,
  server: Server,
  shield: ShieldCheck,
  target: Target,
  upload: Upload,
  userCheck: UserCheck,
  users: Users,
} as const;

export type IconName = keyof typeof icons;

export function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Component = icons[name];
  return <Component aria-hidden="true" strokeWidth={1.6} {...props} />;
}
