/* ==========================================================================
   SITE SETTINGS — company details, navigation and footer links
   --------------------------------------------------------------------------
   ✏️  Edit the text between quotes. Keep the quotes and commas.
   ========================================================================== */

export const site = {
  name: "Node.law",
  // [PLACEHOLDER] Replace with the registered company name once incorporated.
  legalName: "Node.law [Registered entity name]",
  tagline: "AI assistant tools for lawyers and in-house legal teams",
  description:
    "Node.law builds AI assistant tools for in-house counsel, law firms and legal operations teams — draft terms and privacy policies, and review NDAs and commercial contracts with precision.",
  // The live web address. Used for SEO, the sitemap and social sharing previews.
  url: "https://node.law",

  email: "hello@node.law",
  securityEmail: "security@node.law",
  careersEmail: "careers@node.law",
  privacyEmail: "privacy@node.law",

  location: {
    city: "Dubai",
    country: "United Arab Emirates",
    // [PLACEHOLDER] Add a full office address when available.
    address: "Dubai, United Arab Emirates",
  },

  // Add profile links here to show them in the footer. Leave empty to hide.
  social: [
    // { label: "LinkedIn", href: "https://www.linkedin.com/company/your-page" },
  ] as { label: string; href: string }[],

  // Short disclaimer shown in the footer of every page.
  footerDisclaimer:
    "Node.law is not a law firm and does not provide legal advice. Output generated by our tools is not a substitute for advice from a qualified lawyer and must be reviewed before it is relied on.",
};

/* Top navigation (the "Products" menu is built automatically from products.ts) */
export const mainNav = [
  { label: "How it works", href: "/how-it-works" },
  { label: "Security", href: "/security" },
  { label: "Resources", href: "/resources" },
  { label: "About", href: "/about" },
];

/* Footer link columns (a "Products" column is added automatically from products.ts) */
export const footerNav = [
  {
    heading: "Platform",
    links: [
      { label: "How it works", href: "/how-it-works" },
      { label: "Security & Trust", href: "/security" },
      { label: "FAQ", href: "/faq" },
      { label: "Book a demo", href: "/contact" },
    ],
  },
  {
    heading: "Company",
    links: [
      { label: "About us", href: "/about" },
      { label: "Resources", href: "/resources" },
      { label: "Careers", href: "/careers" },
      { label: "Contact", href: "/contact" },
    ],
  },
  {
    heading: "Legal",
    links: [
      { label: "Terms of Service", href: "/legal/terms" },
      { label: "Privacy Policy", href: "/legal/privacy" },
      { label: "Cookie Policy", href: "/legal/cookies" },
      { label: "Disclaimer", href: "/legal/disclaimer" },
      { label: "Acceptable Use & Responsible AI", href: "/legal/acceptable-use" },
      { label: "Data Processing Addendum", href: "/legal/dpa" },
      { label: "Sub-processors", href: "/legal/sub-processors" },
    ],
  },
];
